### ISSUE TITLE
Mis-aligned text

### ISSUE THREAD

**Issue by zspecza** [Gaya/jQuery--Keep-the-Rhythm#1]
Hey, I found your library the other day and decided to play with it, and I'm running into the issue of text below images being pushed off of the grid. The images themselves align just fine. Here's a reproduction using Compass' vertical rhythm module: [Mis-aligned text](http://codepen.io/declandewet/pen/HxrvI) (note the text underneath the image compared to the text on top)

I tried using Dan Eden's `baseline.js` as well and ran into the exact same problem - so I'm very sure this is a problem with my code and not your library, but since you're the author I was wondering if you could help me figure out what I'm doing wrong here?

**Comment by Gaya** [comment]
Hi,

You have to define a height of the image (img height="200" .... />) and you have to make the img a block element in CSS (display: block). That fixed it for me.

Good luck!

Gaya
