### ISSUE TITLE
Question on calling plugin

### ISSUE THREAD

**Issue by adrianvalenz** [Gaya/jQuery--Keep-the-Rhythm#3]
I'm trying to register it using WordPress.

I have two files:
- jquery.keeptherhythm.js , is left untouched
- myrhythm.js , which has this...

$(document).ready(function () {
    $("div.rhythm").keepTheRhythm({
        baseLine: 20
    });
});

$(window).load(function () {
    $("article img").keepTheRhythm({
        baseLine: 20
    });
});

Q: Do I use both or I must choose one? and when I do how do I know what selector to use? I want to target images and video embeds.

and I am using wp_enqueue_scripts to call each in the functions.php file.

I changed the baseline to 24 on the myrhythm.js file but no padding is showing up.

What am I doing wrong?

**Comment by Gaya** [comment]
```
$(document).ready(function () {
    $("div.rhythm, article img").keepTheRhythm({
        baseLine: 20
    });
});
```

Would be best I think. You can keep piling up selectors using `,`. But I guess you already solved your problem?
